/**
 * Web of Life - Planetary Thermodynamic Spatial Types
 * RFC-001 through RFC-045 Comprehensive Retro-Compatibility Layer
 */

// =============================================================================
// HISTORICAL H3 TYPES & CONSTANTS (Sprints 001 - 044)
// =============================================================================

export type H3Index = string;
export type H3Resolution = number;
export type H3ResolutionTier =
  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
  | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;

export enum H3ErrorCode {
  SUCCESS = 'H3_SUCCESS',
  INVALID_LENGTH = 'H3_ERR_INVALID_LENGTH',
  INVALID_CHARACTER = 'H3_ERR_INVALID_CHARACTER',
  INVALID_RESOLUTION = 'H3_ERR_INVALID_RESOLUTION',
  INVALID_BASE_CELL = 'H3_ERR_INVALID_BASE_CELL',
  NULL_INDEX = 'H3_ERR_NULL_INDEX',
}

export class SpatialGuardClauseException extends Error {
  constructor(message: string) {
    super(`[SpatialGuardClauseException] ${message}`);
    this.name = 'SpatialGuardClauseException';
    Object.setPrototypeOf(this, SpatialGuardClauseException.prototype);
  }
}

export interface H3Cell {
  index: string;
  resolution: number;
  mode?: number;
}

export interface IH3TokenExtractor {
  extractTokens(text: string): string[];
}

export interface IH3GridQuery {
  resolution: number;
  baseIndexes?: string[];
  bounds?: { north: number; south: number; east: number; west: number };
}

export interface IH3CellData {
  h3Index: string;
  resolution: number;
  centroid: { lat: number; lng: number };
  solarIrradiance?: number;
  carbonStock?: number;
}

export interface H3ValidationResult {
  isValid: boolean;
  errorCode?: string;
  resolution?: number;
  baseCell?: number;
}

export interface IH3ValidationResult {
  isValid: boolean;
  code: H3ErrorCode;
  message: string;
  resolution?: number;
  baseCell?: number;
}

export interface IResolutionTierValidator {
  validateResolution(resolution: number): boolean;
  assertValidResolution(resolution: number): void;
}

// =============================================================================
// SPRINT 045: THERMODYNAMIC OVERRIDES & TENSOR TYPES
// =============================================================================

/**
 * Physical channel layout indices within H3StateTensor stride buffer.
 */
export enum ThermodynamicChannel {
  TEMPERATURE_KELVIN = 0,
  WATER_MASS_KG = 1,
  SOIL_ORGANIC_CARBON_KG = 2,
  VEGETATION_BIOMASS_KG = 3,
  ATMOSPHERIC_CO2_KG = 4,
  MINERAL_NITROGEN_KG = 5,
  SENSIBLE_HEAT_JOULES = 6,
  ALBEDO = 7,
  CHANNEL_COUNT = 8,
}

/**
 * Standard specific heat capacities (J / kg / K) and enthalpy reference values.
 */
export const THERMODYNAMIC_CONSTANTS = {
  MIN_TEMPERATURE_KELVIN: 2.7315,
  DEFAULT_REGOLITH_MASS_KG: 50_000.0,
  SPECIFIC_HEAT: {
    REGOLITH: 840.0,
    WATER: 4184.0,
    SOIL_ORGANIC_CARBON: 1800.0,
    VEGETATION_BIOMASS: 1900.0,
    ATMOSPHERIC_CO2: 846.0,
    MINERAL_NITROGEN: 1200.0,
  },
  SPECIFIC_ENTHALPY: {
    WATER: -15.87e6,
    SOIL_ORGANIC_CARBON: -32.79e6,
    VEGETATION_BIOMASS: -17.50e6,
    ATMOSPHERIC_CO2: -8.94e6,
    MINERAL_NITROGEN: -2.85e6,
    REGOLITH: 0.0,
  },
} as const;

/**
 * Partial thermodynamic state representing target values or overrides
 * for a single hexagonal cell.
 */
export interface CellThermodynamicOverride {
  temperatureKelvin?: number;
  waterMassKg?: number;
  soilOrganicCarbonKg?: number;
  vegetationBiomassKg?: number;
  atmosphericCo2Kg?: number;
  mineralNitrogenKg?: number;
  sensibleHeatJoules?: number;
  albedo?: number;
}

/**
 * Map or dictionary associating H3 spatial index string to partial override parameters.
 */
export type H3ThermodynamicOverridesMap =
  | Map<string, CellThermodynamicOverride>
  | Record<string, CellThermodynamicOverride>;

/**
 * Auditing record detailing mass and energy delta per modified cell.
 */
export interface CellThermodynamicDeltaRecord {
  h3Index: string;
  cellIndex: number;
  massDeltaKg: number;
  energyDeltaJoules: number;
  thermalEnergyDeltaJoules: number;
  chemicalEnergyDeltaJoules: number;
  overriddenFields: (keyof CellThermodynamicOverride)[];
}

/**
 * Comprehensive ledger generated by applyThermodynamicOverrides.
 */
export interface ThermodynamicOverrideReport {
  timestamp: number;
  cellCountModified: number;
  netMassDeltaKg: number;
  netEnergyDeltaJoules: number;
  netThermalEnergyDeltaJoules: number;
  netChemicalEnergyDeltaJoules: number;
  cellReports: CellThermodynamicDeltaRecord[];
}

/**
 * Behavioral configuration options for applying overrides.
 */
export interface OverrideOptions {
  strictThermodynamicBounds?: boolean;
  minTemperatureKelvin?: number;
  allowMassDestruction?: boolean;
  recomputeSensibleHeat?: boolean;
  regolithMassKg?: number;
  includeChemicalEnthalpy?: boolean;
}